/** Patient app strings. Staff screens stay in English. */
export const PT = {
  en: {
    dir: 'ltr',
    switchTo: 'اردو',
    yourOperation: 'Your operation',
    daysToGo: (n) => (n === 0 ? 'Your operation is today' : n === 1 ? 'Your operation is tomorrow' : `${n} days until your operation`),
    stepsDone: (d, t) => `${d} of ${t} preparation steps done`,
    yourTasks: 'What you need to do',
    teamTasks: 'Your hospital team is handling',
    upload: 'Upload report',
    arranged: 'Donor arranged',
    understood: 'I have done this',
    submitted: 'Sent for checking',
    done: 'Done',
    overdue: 'Overdue',
    dueOn: (d) => `Due ${d}`,
    lateBy: (n) => `${n} day${n === 1 ? '' : 's'} late. Please do this today.`,
    confirmTitle: 'Will you come for your operation?',
    confirmBody: 'Tap to confirm. If you cannot come, please call the surgical ward so the slot can be given to another patient.',
    confirmBtn: 'I will come',
    confirmed: (d) => `You confirmed on ${d}. Thank you.`,
    messages: 'Messages from your doctors',
    reply: 'Write a reply',
    send: 'Send',
    noMessages: 'Instructions from your doctors will appear here.',
    recoveryTitle: 'Your recovery',
    recoveryDay: (d, t) => `Day ${d} of ${t}`,
    checkinDue: 'Your check-in is due today',
    checkinDone: 'Today\'s check-in is done',
    startCheckin: 'Start check-in',
    recalled: 'Your surgeon wants to see you',
    history: 'Your check-ins',
    cancelled: 'Your operation was cancelled',
    deferred: 'Your operation date has changed',
    recovered: 'Your recovery watch is complete',
    noCase: 'You have no operation scheduled.',
    // check-in form
    ciTitle: 'Daily recovery check-in',
    ciIntro: 'Answer a few questions about how you feel today. It takes about one minute.',
    temp: 'Your temperature today (°C)',
    pain: 'How much pain do you have?',
    painHint: '0 = no pain, 10 = worst pain',
    wound: 'How does your wound look?',
    photo: 'Add a photo of the wound (optional)',
    eating: 'Are you eating and drinking?',
    eatNormal: 'Normally', eatReduced: 'Less than usual', eatNone: 'Not at all',
    mobility: 'Can you walk around?',
    mobNormal: 'Yes, normally', mobLimited: 'A little', mobBed: 'No, I stay in bed',
    bleeding: 'Is the wound bleeding?',
    breathless: 'Do you have chest pain or difficulty breathing?',
    yes: 'Yes', no: 'No',
    notes: 'Anything else your doctor should know?',
    submit: 'Send check-in',
    emergencyTitle: 'Go to the Emergency department now',
    emergencyBody: 'What you reported needs urgent attention. Go to the hospital Emergency department now, or call Rescue 1122. Your surgical team has been alerted.',
    alertTitle: 'Your surgical team has been alerted',
    alertBody: 'Some of your answers need a doctor\'s review. The team will contact you today. If you feel worse, go to the Emergency department.',
    okTitle: 'Thank you. Your recovery looks on track',
    okBody: 'Your answers were saved. Keep following your discharge advice.',
    backHome: 'Back to my surgery',
    notMonitoring: 'Check-ins start after you are discharged from hospital.',
    general: 'Overall, how do you feel compared with yesterday?',
    better: 'Better', same: 'About the same', worse: 'Worse',
    symptomsLabel: 'Do you have any of these symptoms?',
    symptoms: { Fever: 'Fever or chills', Nausea: 'Nausea or vomiting', Swelling: 'Wound redness or swelling', Pain: 'Pain getting worse', Dizziness: 'Dizziness or fainting', Urine: 'Difficulty passing urine' },
    disclaimer: 'MedSync does not diagnose. Your answers are reviewed by your surgical team. In an emergency go to the Emergency department or call Rescue 1122.',
    sending: 'Sending…',
    medicinesTitle: 'Medicines before surgery',
    medicinesBody: 'Follow the medicine instructions from your anaesthetist in the messages below. Do not stop or start any medicine on your own.',
    dayTitle: 'On the day of your operation',
    dayBody: 'Come to the admission desk with your attendant, hospital card and reports. Follow the fasting instruction.',
  },
  ur: {
    dir: 'rtl',
    switchTo: 'English',
    yourOperation: 'آپ کا آپریشن',
    daysToGo: (n) => (n === 0 ? 'آپ کا آپریشن آج ہے' : n === 1 ? 'آپ کا آپریشن کل ہے' : `آپ کے آپریشن میں ${n} دن باقی ہیں`),
    stepsDone: (d, t) => `تیاری کے ${t} میں سے ${d} مراحل مکمل`,
    yourTasks: 'آپ کو یہ کرنا ہے',
    teamTasks: 'ہسپتال کی ٹیم یہ کام کر رہی ہے',
    upload: 'رپورٹ اپ لوڈ کریں',
    arranged: 'خون دینے والے کا انتظام ہو گیا',
    understood: 'میں نے یہ کر لیا',
    submitted: 'جانچ کے لیے بھیج دیا گیا',
    done: 'مکمل',
    overdue: 'تاخیر',
    dueOn: (d) => `آخری تاریخ ${d}`,
    lateBy: (n) => `${n} دن کی تاخیر۔ براہ کرم آج ہی کریں۔`,
    confirmTitle: 'کیا آپ آپریشن کے لیے آئیں گے؟',
    confirmBody: 'تصدیق کے لیے بٹن دبائیں۔ اگر نہیں آ سکتے تو سرجیکل وارڈ کو فون کریں تاکہ یہ وقت کسی اور مریض کو دیا جا سکے۔',
    confirmBtn: 'میں آؤں گا / آؤں گی',
    confirmed: (d) => `آپ نے ${d} کو تصدیق کی۔ شکریہ۔`,
    messages: 'آپ کے ڈاکٹروں کے پیغامات',
    reply: 'جواب لکھیں',
    send: 'بھیجیں',
    noMessages: 'آپ کے ڈاکٹروں کی ہدایات یہاں نظر آئیں گی۔',
    recoveryTitle: 'آپ کی صحت یابی',
    recoveryDay: (d, t) => `${t} میں سے دن ${d}`,
    checkinDue: 'آج کا چیک اِن باقی ہے',
    checkinDone: 'آج کا چیک اِن مکمل ہے',
    startCheckin: 'چیک اِن شروع کریں',
    recalled: 'آپ کے سرجن آپ کو دیکھنا چاہتے ہیں',
    history: 'آپ کے چیک اِن',
    cancelled: 'آپ کا آپریشن منسوخ ہو گیا',
    deferred: 'آپ کے آپریشن کی تاریخ بدل گئی ہے',
    recovered: 'آپ کی نگرانی مکمل ہو گئی',
    noCase: 'آپ کا کوئی آپریشن طے نہیں ہے۔',
    ciTitle: 'روزانہ صحت چیک اِن',
    ciIntro: 'آج آپ کیسا محسوس کر رہے ہیں، چند سوالوں کے جواب دیں۔ صرف ایک منٹ لگے گا۔',
    temp: 'آج آپ کا بخار (°C)',
    pain: 'آپ کو کتنا درد ہے؟',
    painHint: '0 = کوئی درد نہیں، 10 = شدید ترین درد',
    wound: 'آپ کا زخم کیسا دکھتا ہے؟',
    photo: 'زخم کی تصویر شامل کریں (اختیاری)',
    eating: 'کیا آپ کھا پی رہے ہیں؟',
    eatNormal: 'معمول کے مطابق', eatReduced: 'معمول سے کم', eatNone: 'بالکل نہیں',
    mobility: 'کیا آپ چل پھر سکتے ہیں؟',
    mobNormal: 'ہاں، معمول کے مطابق', mobLimited: 'تھوڑا سا', mobBed: 'نہیں، بستر پر ہوں',
    bleeding: 'کیا زخم سے خون بہہ رہا ہے؟',
    breathless: 'کیا سینے میں درد یا سانس لینے میں دشواری ہے؟',
    yes: 'ہاں', no: 'نہیں',
    notes: 'کوئی اور بات جو ڈاکٹر کو معلوم ہونی چاہیے؟',
    submit: 'چیک اِن بھیجیں',
    emergencyTitle: 'ابھی ایمرجنسی جائیں',
    emergencyBody: 'آپ نے جو بتایا اس پر فوری توجہ ضروری ہے۔ ابھی ہسپتال کی ایمرجنسی جائیں یا ریسکیو 1122 کو کال کریں۔ آپ کی سرجیکل ٹیم کو اطلاع دے دی گئی ہے۔',
    alertTitle: 'آپ کی سرجیکل ٹیم کو اطلاع دے دی گئی ہے',
    alertBody: 'آپ کے کچھ جوابات ڈاکٹر کو دیکھنے ہیں۔ ٹیم آج آپ سے رابطہ کرے گی۔ اگر طبیعت زیادہ خراب ہو تو ایمرجنسی جائیں۔',
    okTitle: 'شکریہ۔ آپ کی صحت یابی ٹھیک جا رہی ہے',
    okBody: 'آپ کے جوابات محفوظ ہو گئے۔ ڈسچارج کی ہدایات پر عمل جاری رکھیں۔',
    backHome: 'واپس جائیں',
    notMonitoring: 'چیک اِن ہسپتال سے ڈسچارج کے بعد شروع ہوں گے۔',
    general: 'کل کے مقابلے میں آج آپ کیسا محسوس کر رہے ہیں؟',
    better: 'بہتر', same: 'تقریباً ویسا ہی', worse: 'زیادہ خراب',
    symptomsLabel: 'کیا آپ کو ان میں سے کوئی علامت ہے؟',
    symptoms: { Fever: 'بخار یا کپکپی', Nausea: 'متلی یا الٹی', Swelling: 'زخم پر سرخی یا سوجن', Pain: 'درد بڑھ رہا ہے', Dizziness: 'چکر یا بے ہوشی', Urine: 'پیشاب میں دشواری' },
    disclaimer: 'میڈ سِنک تشخیص نہیں کرتا۔ آپ کے جوابات آپ کی سرجیکل ٹیم دیکھتی ہے۔ ایمرجنسی میں ہسپتال کی ایمرجنسی جائیں یا ریسکیو 1122 کو کال کریں۔',
    sending: 'بھیجا جا رہا ہے…',
    medicinesTitle: 'آپریشن سے پہلے دوائیں',
    medicinesBody: 'نیچے پیغامات میں بے ہوشی کے ڈاکٹر کی ہدایات پر عمل کریں۔ خود سے کوئی دوا بند یا شروع نہ کریں۔',
    dayTitle: 'آپریشن کے دن',
    dayBody: 'اپنے ساتھی، ہسپتال کارڈ اور رپورٹس کے ساتھ داخلہ ڈیسک پر آئیں۔ روزے (فاقے) کی ہدایت پر عمل کریں۔',
  },
};
